### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS error when many objects in one image

### ISSUE THREAD

**Issue by Lizw14** [yangxue0827/R-DFPN_FPN_Tensorflow#5]
Hi,

I encountered the problem of CUDA_ERROR_ILLEGAL_ADDRESS error during training when the objects are densely located, i.e. when there are many(roughly >100 or 150) ships in one 600*1000 image. When I split these dense images into smaller ones(control object number < 50) and pad the splitted images into 600*1000, the training goes on well with no error. BTW, the same error happens in all your repositories(R2CNN, RRPN, R-DFPN). 

But I think split the images with densely located objects may damage the final performance, so I want to get this problem solved. Could you please tell me which part cause this error? Maybe GPU NMS or something else?

![wechatimg7](https://user-images.githubusercontent.com/20157670/39224114-14c01ec6-4878-11e8-9e23-f96a7a6bd71e.jpeg)

**Comment by FishBigOcean** [comment]
> Hi,
> 
> I encountered the problem of CUDA_ERROR_ILLEGAL_ADDRESS error during training when the objects are densely located, i.e. when there are many(roughly >100 or 150) ships in one 600_1000 image. When I split these dense images into smaller ones(control object number < 50) and pad the splitted images into 600_1000, the training goes on well with no error. BTW, the same error happens in all your repositories(R2CNN, RRPN, R-DFPN).
> 
> But I think split the images with densely located objects may damage the final performance, so I want to get this problem solved. Could you please tell me which part cause this error? Maybe GPU NMS or something else?
> 
> ![wechatimg7](https://user-images.githubusercontent.com/20157670/39224114-14c01ec6-4878-11e8-9e23-f96a7a6bd71e.jpeg)

Thanks for sharing！
Did you finally find a solution other than cropping the picture?
look forward to your reply

**Comment by zsh1234567** [comment]
May I ask what dataset set do you use?
